import requests
import json
import os
import concurrent.futures

from tqdm import tqdm
import evaluate


"""gpt4 retrieved docs: The Rock and Roll Hall of Fame, located in downtown Cleveland, Ohio, on the shore of Lake Erie, recognizes and archives the history of the best-known and most influential artists, producers, engineers, and other notable figures who have had some major influence on the development of rock and roll. The Rock and Roll Hall of Fame Foundation was established on April 20, 1983, by Ahmet Ertegun, founder and chairman of Atlantic Records. In 1986, Cleveland was chosen as the Hall of Fame's permanent home.
#In 2014, Cumberland Development, LLC and Trammel Crow Company were selected by City of Cleveland to develop 20+ acres surrounding Cleveland's North Coast Harbor. Phase 1; a restaurant on E9th pier was complete July 2016. Ground breaking for Phase 2; multi-use space located in the former skate park just north of the Rock & Roll Hall of Fame is scheduled for 2017.
#Public Auditorium (also known as Public Hall) is a multi-purpose performing arts, entertainment, sports, and exposition facility located in the civic center district of downtown Cleveland, Ohio. The 10,000-capacity main auditorium shares its stage with a second venue housed at the facility: the 3,000-capacity Music Hall. Although Public Auditorium was planned and funded prior to World War I, construction did not begin until 1920, and the building did not open until 1922. Designed by city architect J. Harold McDowell and Frank Walker of Walker and Weeks in a neoclassical style matching the other Group Plan buildings, it was the largest of its kind when opened, then seating 11,500.
#Rock and Roll Hall of Fame, Cleveland, Ohio- November 15, 2006- April 15, 2007,
#On August 28, 2011, a memorial service was held for Jane Scott at the Rock and Roll Hall of Fame and Museum, which was attended by over 900 people, and included speakers from local Cleveland music industry, family and friends. On July 5, 2012, the Rock Hall unveiled a lifesize bronze memorial statue, which has been permanently installed in the Reading Room of the Rock Hall's Library & Archives. The statue was created by Cleveland area sculptor and past president of the Cleveland Institute of Art, David Deming. The Rock Hall also announced the completion of an agreement with the Scott family for the Rock Hall's Library & Archives to acquire Scott's papers, notebooks, and photos relating to her music journalism career in Cleveland.
#On January 23, 1986, Freed was part of the first group inducted into the Rock and Roll Hall of Fame in Cleveland. In 1988, he was also posthumously inducted into the National Radio Hall of Fame. On December 10, 1991, Freed was given a star on the Hollywood Walk of Fame. The VH1 series "Behind The Music" produced an episode on Freed featuring Roger Steffens. In 1998 The Official Website of Alan Freed went online with the jumpstart from Brian Levant and Michael Ochs archives as well as a home page biography written by Ben Fong-Torres. On February 26, 2002, Freed was honored at the Grammy Awards with the Trustees Award. In 2017 he was inducted into the Rhythm & Blues Hall of Fame in Detroit, Michigan. 
#While at WMMS, Kid Leo became involved in the campaign to bring the Rock and Roll Hall of Fame to Cleveland. For his efforts in helping secure the Rock Hall, former Cleveland mayor and then-Ohio governor George Voinovich presented him with the key to the city in 1990. His on-air work is represented as part of the permanent radio exhibit in the Rock and Roll Hall of Fame.
#In addition to his involvement with Cleveland's Hall of Fame, on October 7, 2007, Spero himself was inducted as one of the Radio/Television Broadcasters Hall of Fame of Ohio's Class of 2007. And when Graham Nash was inducted into the Rock and Roll Hall of Fame in 2010 for the second time, this time with The Hollies – the first time was in 1997 with Crosby, Stills and Nash – Nash acknowledged the help and support of Spero during his remarks.
#The Rock and Roll Hall of Fame, established in 1983 and located in Cleveland, Ohio, United States, is dedicated to recording the history of some of the best-known and most influential musicians, bands, producers, and others that have in some major way influenced the music industry, particularly in the area of rock and roll. Originally, there were four categories of induction: performers, non-performers, early influences, and lifetime achievement. In 2000, "sidemen" was introduced as a category.
#Norm N. Nite (born Norman Durma, January 25, 1941), is the author of the "Rock On: The Illustrated Encyclopedia of Rock N' Roll" book series. Nite began his career as a DJ at WGAR (AM) in Cleveland and later at WMJI there. Later he would host shows at WCBS-FM and WNBC in New York City. His historical interest in Rock & Roll led him to compile, as the first volume of "Rock On" describes it, "an exhaustive array of data on more than 1,000 of the most popular artists of the fifties and early sixties. Any singer who had a top 100 single during the golden days of rock n' roll can be found in (the) book." Subsequently, due to the popularity of this volume, first released in 1974, he authored a second volume in 1978, covering, as described on the dust jacket, "The Modern Years: 1964-Present" with an introduction by Wolfman Jack. In 1985 Rock On Volume 3 was released and billed "Rock On Volume 3 – The Video Revolution: 1978 – Present". During 1988 he narrated the radio program, Solid Gold Scrapbook.
#Artists are inducted into the Rock and Roll Hall of Fame at an annual induction ceremony. Over the years, the majority of the ceremonies have been held at the Waldorf-Astoria Hotel in New York City. However, on January 12, 1993, the ceremony was held in Los Angeles, and was held there again in 2013. On May 6, 1997, about a year and a half after the opening of the Rock and Roll Hall of Fame and Museum, the ceremony was held in Cleveland. It returned to Cleveland in 2009 and again in 2012. Current plans call for the ceremony to be in Cleveland every three years. 
#On March 19, 2012, Cleveland City Council approved key pieces of Mayor Frank Jackson's lakefront plan, a development plan to transform the waterfront by remaking the shoreline from the Cuyahoga River east across Burke Lakefront Airport, while building on existing attractions, such as the East Ninth Street pier, the Rock and Roll Hall of Fame and Museum, the Great Lakes Science Center and FirstEnergy Stadium. Architectural drawings include shops, restaurants, offices and a hotel tied together by walking and bicycle paths. The Rock & Dock at the North Coast Harbor Transient Marina in Downtown Cleveland opened behind the Rock and Roll Hall of Fame and Museum in June 2014.
#The Greater Cleveland Sports Hall of Fame displays duplicates of many of the plaques it has awarded in the lobby at the Lakeside Avenue entrance to the Cleveland Public Auditorium.
#Rock and Roll Hall of Fame – Cleveland, Ohio- May 2002 – September 2002, 
#On March 21, 1952, Cleveland disc jockey Alan Freed promoted The Moondog Coronation Ball at the Cleveland Arena which is recognized as the first rock and roll concert, but Scott was not in attendance at this historic show. Three days later, on March 24, 1952, at age 33, Scott was hired as an assistant society reporter at "The Plain Dealer", covering the local social scene of A-List weddings and Debutante Balls. After two years as a general reporter, Scott got her own column called "Senior Class," covering topics of interest to senior citizens, which she wrote for almost twenty years.
#Freed died in a Palm Springs, California, hospital on January 20, 1965, from uremia and cirrhosis brought on by alcoholism; he was 43 years old, and was initially interred in the Ferncliff Cemetery in Hartsdale, New York. In March 2002, Judith Fisher Freed carried his ashes to the Rock and Roll Hall of Fame in Cleveland, Ohio. On August 1, 2014, the Hall of Fame asked Alan Freed's son, Lance Freed, to permanently remove the ashes, which he did. The Freed family later announced the ashes would be interred at Cleveland's Lake View Cemetery.
#Kid Leo started at WMMS in February, 1973. He became the afternoon drive DJ in 1974, holding that time slot until he left the station in December, 1988. In 1977 he was promoted to Music Director, then assumed the Operations Manager position in 1986. “To many, Kid Leo "was" WMMS. For sixteen years he was the pulse of the station, pumping music and life into the veins of listeners.” He was known for embracing new acts, and was credited with breaking many artists in the Cleveland market and giving them more advantage with greater national exposure. Some of those artists were Bruce Springsteen, John Mellencamp, Pat Benatar, Roxy Music, Cyndi Lauper, The Pretenders, New York Dolls, and Southside Johnny. 
#In 2000, Spero accepted a position as Senior Director of Programming for The Rock and Roll Hall of Fame where he set up many shows and creative events including "MTV Live At The Rock and Roll Hall of Fame". John Mayer, Linkin Park, Avril Lavigne and Godsmack are among the artists Spero brought to the Rock Hall. Spero served as a member of their Board of Trustees into 2008. Among the many events he brought to the Rock Hall, in October, 2005, Spero recreated "Upbeat" in a benefit helping inner city teenagers.
#List of Rock and Roll Hall of Fame inductees
#In July 2005 Nite began broadcasting live from the Rock and Roll Hall of Fame in Cleveland on SIRIUS Satellite Radio Channel 5 (SIRIUS Gold, now known as Sirius XM 50s on 5), which is also available on channel 9905 on the Dish Network. His show had originally aired Wednesdays through Sundays, but in August 2006, he cut back his on-air schedule to every Friday through Sunday afternoons from 3-6 p.m. US Eastern time (12-3 p.m. Pacific time)."""

"""v0105 retrieved docs: The Rock and Roll Hall of Fame, located in downtown Cleveland, Ohio, on the shore of Lake Erie, recognizes and archives the history of the best-known and most influential artists, producers, engineers, and other notable figures who have had some major influence on the development of rock and roll. The Rock and Roll Hall of Fame Foundation was established on April 20, 1983, by Ahmet Ertegun, founder and chairman of Atlantic Records. In 1986, Cleveland was chosen as the Hall of Fame's permanent home.
#On August 28, 2011, a memorial service was held for Jane Scott at the Rock and Roll Hall of Fame and Museum, which was attended by over 900 people, and included speakers from local Cleveland music industry, family and friends. On July 5, 2012, the Rock Hall unveiled a lifesize bronze memorial statue, which has been permanently installed in the Reading Room of the Rock Hall's Library & Archives. The statue was created by Cleveland area sculptor and past president of the Cleveland Institute of Art, David Deming. The Rock Hall also announced the completion of an agreement with the Scott family for the Rock Hall's Library & Archives to acquire Scott's papers, notebooks, and photos relating to her music journalism career in Cleveland.
#In 2014, Cumberland Development, LLC and Trammel Crow Company were selected by City of Cleveland to develop 20+ acres surrounding Cleveland's North Coast Harbor. Phase 1; a restaurant on E9th pier was complete July 2016. Ground breaking for Phase 2; multi-use space located in the former skate park just north of the Rock & Roll Hall of Fame is scheduled for 2017.
#Rock and Roll Hall of Fame, Cleveland, Ohio- November 15, 2006- April 15, 2007,
#In addition to his involvement with Cleveland's Hall of Fame, on October 7, 2007, Spero himself was inducted as one of the Radio/Television Broadcasters Hall of Fame of Ohio's Class of 2007. And when Graham Nash was inducted into the Rock and Roll Hall of Fame in 2010 for the second time, this time with The Hollies – the first time was in 1997 with Crosby, Stills and Nash – Nash acknowledged the help and support of Spero during his remarks.
#The Greater Cleveland Sports Hall of Fame displays duplicates of many of the plaques it has awarded in the lobby at the Lakeside Avenue entrance to the Cleveland Public Auditorium.
#The Rock and Roll Hall of Fame awarded Bobby Bennett, and the other members of The Famous Flames, Bobby Byrd, Lloyd Stallworth, and Johnny Terry, posthumously on April 14, 2012.
#On January 23, 1986, Freed was part of the first group inducted into the Rock and Roll Hall of Fame in Cleveland. In 1988, he was also posthumously inducted into the National Radio Hall of Fame. On December 10, 1991, Freed was given a star on the Hollywood Walk of Fame. The VH1 series "Behind The Music" produced an episode on Freed featuring Roger Steffens. In 1998 The Official Website of Alan Freed went online with the jumpstart from Brian Levant and Michael Ochs archives as well as a home page biography written by Ben Fong-Torres. On February 26, 2002, Freed was honored at the Grammy Awards with the Trustees Award. In 2017 he was inducted into the Rhythm & Blues Hall of Fame in Detroit, Michigan. 
#Robinson was emcee for the Elvis Presley show at Empire Stadium in Vancouver in 1957 and for the Beatles in 1964. He also became the program director of two Vancouver radio stations, CFUN from 1962 to 1968 and CJOR from 1968 to 1970. Over the years, he worked at many radio and TV stations in Vancouver and Portland, including CKWX, KGW, KGW-TV, CFUN, and the CBC, CISL (twice) as well as CFUN-FM. He also served in the United States Army until his honourable discharge. He has co-authored two books, "Rockbound" and "Backstage Vancouver." "Rockbound" is his personal accounts of early rock and roll. "Backstage Vancouver" looks at the rich history of entertainment in Vancouver.
#On September 24, 2010, the Rock and Roll Hall of Fame and Museum designated J&M Recording Studio a historic Rock and Roll Landmark, one of 11 nationwide.
#The song was chosen as one of The Rock and Roll Hall of Fame's 500 Songs that Shaped Rock and Roll. An accompanying album, "Oh! Suzy Q " was released in 1958. Creedence Clearwater Revival's version of the song on their 1968 debut album helped launch their career and today it is probably the best-known version.
#The station was designed by the firm of Robert P. Madison International, founded by the prominent African American architect. It was designed to harmonize with the style of the nearby Rock and Roll Hall of Fame, for which the Madison firm was also associate architects.
#The Miracles have four songs on "The Rock and Roll Hall of Fame's 500 Songs that Shaped Rock and Roll" list:
#Significant works of the firm through 2005 include John F. Kennedy Library, John Hancock Tower, and John Joseph Moakley United States Courthouse and Harborpark in Boston; J.P. Morgan Chase Tower in Houston, Dallas City Hall, the Morton H. Meyerson Symphony Center, and Fountain Place in Dallas; Bank of China Tower in Hong Kong; U.S. Bank Tower in Los Angeles; First Bank Place in Minneapolis; Jacob K. Javits Convention Center in New York; National Constitution Center on Independence Mall in Philadelphia; Rock and Roll Hall of Fame and Museum in Cleveland, the expansion and modernization of the Louvre museum in Paris; San Francisco Main Public Library; and the East Building of the National Gallery of Art, the Ronald Reagan Building and International Trade Center and the United States Holocaust Memorial Museum in Washington, D.C.
#! 1995
#A back wall of the building has the autographs of performers who played there. Artist who performed at The Col include: Duke Ellington, B.B. King, the Everly Brothers, The Beach Boys, Little Richard, Chuck Berry, Johnny Cash, Muddy Waters, Jimi Hendrix, and Stevie Ray Vaughan. The Col Ballroom was added to the National Register of Historic Places in 1983, the Davenport Register of Historic Properties in 1998, and it was inducted into the Iowa Rock and Roll Music Association hall of fame in 1999. The venue is slated to close as a ballroom and performance venue on October 29, 2018.
#Balthazar Korab
#On February 9, 2012, it was announced that Bobby Rogers would be inducted with the rest of the Miracles into the Rock and Roll Hall of Fame alongside Miracles lead singer Smokey Robinson. This induction occurred on April 14, 2012. After a 26-year wait, Bobby was automatically and retroactively inducted with the rest of the original Miracles, Marv Tarplin, Pete Moore, Claudette Robinson, and Ronnie White into The Rock and Roll Hall of Fame alongside Miracles lead singer Smokey Robinson. The induction was handled by a Special Committee designated by The Rock Hall in 2012, that inducted the Miracles, and five other deserving pioneering groups, that were overlooked when their lead singers were inducted into the Rock Hall many years ago. This induction occurred without the usual process of nomination and voting, under the premise that "the entire group" should have been inducted with Smokey Robinson back in 1987.
#In 1929, the Board of Education voted to build a new Wendell Phillips High School (which later became DuSable High School) at 49th and Wabash Avenue. Economic conditions during the Great Depression slowed the work on the building; it was finally completed February 4, 1935. The old school "mysteriously" caught fire January 28, 1935, making it necessary for the students to move to the new school in February 1935. Now located at 244 E. Pershing Road in the Bronzeville neighborhood of Chicago, the school has produced a number of notable African-American alumni, including Nat "King" Cole, singing legend and charter member of the Rock and Roll Hall of Fame; the singer Sam Cooke; and George E. Johnson, Sr., founder of Johnson Products (he was a cosmetics manufacturer and his was the first African-American owned firm to be listed on the American Stock Exchange). Constructed in 1904 in the Classical Revival style, the school building was designated a Chicago Landmark on May 7, 2003 in time for its 100th anniversary. Phillips was used as the setting and shooting location for the movie "Save the Last Dance," released in 2001.
#AARP Awards"""